before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
